/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.github.jeqo.poc.schema.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class MyOtherRecord extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8619756975539070558L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"MyOtherRecord\",\"namespace\":\"io.github.jeqo.poc.schema.avro\",\"fields\":[{\"name\":\"f1\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<MyOtherRecord> ENCODER =
      new BinaryMessageEncoder<MyOtherRecord>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<MyOtherRecord> DECODER =
      new BinaryMessageDecoder<MyOtherRecord>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<MyOtherRecord> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<MyOtherRecord> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<MyOtherRecord>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this MyOtherRecord to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a MyOtherRecord from a ByteBuffer. */
  public static MyOtherRecord fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence f1;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public MyOtherRecord() {}

  /**
   * All-args constructor.
   * @param f1 The new value for f1
   */
  public MyOtherRecord(java.lang.CharSequence f1) {
    this.f1 = f1;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return f1;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: f1 = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'f1' field.
   * @return The value of the 'f1' field.
   */
  public java.lang.CharSequence getF1() {
    return f1;
  }

  /**
   * Sets the value of the 'f1' field.
   * @param value the value to set.
   */
  public void setF1(java.lang.CharSequence value) {
    this.f1 = value;
  }

  /**
   * Creates a new MyOtherRecord RecordBuilder.
   * @return A new MyOtherRecord RecordBuilder
   */
  public static io.github.jeqo.poc.schema.avro.MyOtherRecord.Builder newBuilder() {
    return new io.github.jeqo.poc.schema.avro.MyOtherRecord.Builder();
  }

  /**
   * Creates a new MyOtherRecord RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new MyOtherRecord RecordBuilder
   */
  public static io.github.jeqo.poc.schema.avro.MyOtherRecord.Builder newBuilder(io.github.jeqo.poc.schema.avro.MyOtherRecord.Builder other) {
    return new io.github.jeqo.poc.schema.avro.MyOtherRecord.Builder(other);
  }

  /**
   * Creates a new MyOtherRecord RecordBuilder by copying an existing MyOtherRecord instance.
   * @param other The existing instance to copy.
   * @return A new MyOtherRecord RecordBuilder
   */
  public static io.github.jeqo.poc.schema.avro.MyOtherRecord.Builder newBuilder(io.github.jeqo.poc.schema.avro.MyOtherRecord other) {
    return new io.github.jeqo.poc.schema.avro.MyOtherRecord.Builder(other);
  }

  /**
   * RecordBuilder for MyOtherRecord instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<MyOtherRecord>
    implements org.apache.avro.data.RecordBuilder<MyOtherRecord> {

    private java.lang.CharSequence f1;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.github.jeqo.poc.schema.avro.MyOtherRecord.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.f1)) {
        this.f1 = data().deepCopy(fields()[0].schema(), other.f1);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing MyOtherRecord instance
     * @param other The existing instance to copy.
     */
    private Builder(io.github.jeqo.poc.schema.avro.MyOtherRecord other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.f1)) {
        this.f1 = data().deepCopy(fields()[0].schema(), other.f1);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'f1' field.
      * @return The value.
      */
    public java.lang.CharSequence getF1() {
      return f1;
    }

    /**
      * Sets the value of the 'f1' field.
      * @param value The value of 'f1'.
      * @return This builder.
      */
    public io.github.jeqo.poc.schema.avro.MyOtherRecord.Builder setF1(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.f1 = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'f1' field has been set.
      * @return True if the 'f1' field has been set, false otherwise.
      */
    public boolean hasF1() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'f1' field.
      * @return This builder.
      */
    public io.github.jeqo.poc.schema.avro.MyOtherRecord.Builder clearF1() {
      f1 = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public MyOtherRecord build() {
      try {
        MyOtherRecord record = new MyOtherRecord();
        record.f1 = fieldSetFlags()[0] ? this.f1 : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<MyOtherRecord>
    WRITER$ = (org.apache.avro.io.DatumWriter<MyOtherRecord>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<MyOtherRecord>
    READER$ = (org.apache.avro.io.DatumReader<MyOtherRecord>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
